### ISSUE TITLE
Bug avec la PWA

### ISSUE THREAD

**Issue by borisschapira** [sudweb/2018#31]
### Comportement constaté

* Les ressources statiques ne sont pas chargées quand on arrive d'une autre page du même domaine, mais qui n'appartient pas à https://sudweb.fr/2018/. Par exemple https://sudweb.fr/blog/

### Comportement attendu

* Les ressources statiques sont chargées

### Étapes pour reproduire le problème

- Aller sur https://sudweb.fr/blog/2018/les-tarifs-de-sud-web-2018/
- Cliquer sur le lien "appel à sujets"

@sudweb/thym

**Comment by borisschapira** [comment]
Je n'arrive plus à reproduire le bug, et je ne sais pas pourquoi…

![](https://media.giphy.com/media/VXCPgZwEP7f1e/giphy.gif)

**Comment by nhoizey** [comment]
?

**Comment by borisschapira** [comment]
Matthieu a eu un bug à nouveau (sur /2018/humans.txt), et je ne sais pas comment résoudre. Changer le scope sur "/" donne un résultat pire. L'invalidation du cache n'est pas satisfaisante en l'état.
