### ISSUE TITLE
Fond clair sur le favicon

### ISSUE THREAD

**Issue by borisschapira** [sudweb/2018#57]
### Comportement constaté

@dirtyF: 

> le favicon transparent est très difficile à cerner sur mon téléphone quand j’ajoute un raccourci sur l’écran d’accueil

### Comportement attendu

@dirtyF : 

> un fond clair sinon rien

### Étapes pour reproduire le problème

@sudweb/thym

**Comment by DirtyF** [comment]
### étapes pour reproduire le problème

* Ajouter le site à l'écran d'accueil sur son mobile avec une photo d'arrière-plan aux teintes vertes
* Jouer à trouver la favicon de Sud Web

**Comment by borisschapira** [comment]
Fixed by 782553cb216d69c1bfde7bc474203f6b93b52a78
