### ISSUE TITLE
Ajouter le déplacement en vélo

### ISSUE THREAD

**Issue by GaspardPO** [sudweb/2018#84]
### Comportement constaté
Dans "venir à Sud Web", il manque le vélo.

Depuis Alès, ça ne ferait que 18&nbsp;km et 140&nbsp;m de dénivelé positif (160&nbsp;m en évitant la D910a), donc une petite heure d'après [cycle.travel](http://cycle.travel/map?from=Al%C3%A8s&to=Chemin%20Bas%2C%20Anduze%2C%20Al%C3%A8s%2C%20Gard%2C%20Occitanie%2C%20France%20m%C3%A9tropolitaine%2C%2030140%2C%20France&fromLL=&toLL).

Depuis Nimes, ça semble être une quarantaine de kilomètres et 400&nbsp;m de dénivelé positif.

Et le Gard en mai, ça doit être sympa à pédaler !

@sudweb/thym

Si j'ai le temps, je fais une Pull Request avec un itinéraire dans la semaine.

**Comment by borisschapira** [comment]
Ça serait une chouette PR, en effet !
