### ISSUE TITLE
Les bannières ne s'affichent pas sur iPhone 6S (ou mal)

### ISSUE THREAD

**Issue by borisschapira** [sudweb/2018#85]
Bug remonté par @skyounet https://twitter.com/Skyounet/status/968163440798961666
Constaté sur iPhone 6S, iOS 11.2.5, Safari 11.0

### Comportement constaté

- Flou au chargement des bannières (je soupçonne un mauvais positionnement des fonds)

![dw-bgrlx4aejmbj](https://user-images.githubusercontent.com/284742/36694045-6217399c-1b3d-11e8-9156-4e6993eec2d8.jpg)
![dw-bgwfx4aal4m0](https://user-images.githubusercontent.com/284742/36694046-6236bf56-1b3d-11e8-9c56-5818b52560e7.jpg)

### Comportement attendu

- Soit un comportement homogène, soit testé le support des règles CSS utilisées pour afficher, en cas de non-support, une version non-fixée-masque de la bannière.

### Étapes pour reproduire le problème

- Consulter le site sur iPhone 6S

@sudweb/thym

**Comment by Twikito** [comment]
Oui, c'est un problème entre background-size: cover et background-attachement: fixed, que je croyais corrigé depuis longtemps, mais apparemment toujours pas sur iOS -_-v
